# baseURL = "http://localhost/dynamic365Build/jp/dynamic/"
baseURL = "https://amptest.ameio.in/jp/dynamic/"
DefaultContentLanguage = "jp"
defaultContentLanguageInSubdir = false

[params]
    oppositeUrl = "https://amptest.ameio.in/en/dynamic/"