# baseURL = "http://localhost/dynamic365Build/jp/dynamic/"
# baseURL = "https://amptest.ameio.in/jp/dynamic/"
baseURL = "http://localhost/dynamiclive/jp/dynamic/"

DefaultContentLanguage = "jp"
defaultContentLanguageInSubdir = false

[params]
    oppositeUrl = "http://localhost/dynamiclive/en/dynamic/"
    env = "devlop"  