# baseURL = "http://localhost/dynamic365Build/en/dynamic/"
# baseURL = "https://amptest.ameio.in/"
baseURL = "http://localhost/dynamic365Imagetesting/"

languageCode = "en-us"
title = "My New Hugo Site"
theme = "hugoDynamic365Theme"
timeout = 300000
[Languages]
############ 1 - Site en Japanese
[Languages.jp]
languageName = "JP"
weight = 1
languageCode = "jp-jp"

############ 1 - Site en Japanese
[Languages.en]
languageName = "EN"
weight = 2
languageCode = "en-en"


[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

[params]
headerTitle = "Dynamics 365 blog"
env = "devlop"
imageratio = "1 2"
imagewidth = "700"