# baseURL = "http://localhost/dynamic365Imagetesting/"

defaultContentLanguageInSubdir = true
DefaultContentLanguage = "en"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "hugoDynamic365Theme"
timeout = 300000
[Languages]
############ 1 - Site en Japanese
[Languages.ja]
languageName = "JA"
weight = 1
languageCode = "ja-JP"

############ 1 - Site en Japanese
[Languages.en]
languageName = "EN"
weight = 2
languageCode = "en-us"


[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

[params]
  headerTitle = "Dynamics 365 blog"
  env = "devlop"
  imageratio = "1"
  imagewidth = "700"