baseURL = "https://www.andaze.com/dynamics365/"

defaultContentLanguageInSubdir = true
DefaultContentLanguage = "en"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "hugoDynamic365Theme"
timeout = 300000
googleAnalytics = "UA-144087233-8" # your analitics ID

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "date", "author", "permalink", "content"]

[outputs]
home = ["HTML", "RSS", "Algolia"]

[Languages]
############ 1 - Site en Japanese
[Languages.ja]
languageName = "JA"
weight = 1
languageCode = "ja-JP"
fillposition = "center"
format= "webp"

############ 1 - Site en Japanese
[Languages.en]
languageName = "EN"
weight = 2
languageCode = "en-us"
fillposition = "center"
format= "webp"

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

[params]
  headerTitle = "Dynamics 365 blog"
  env = "devlop"
  imageratio = "1 1.5 2 3"
  imagewidth = "700"