baseURL = "https://amptest.ameio.in/en/dynamic/"
DefaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[params]
    oppositeUrl = "https://amptest.ameio.in/jp/dynamic/"
    env = "prod"  