baseURL = "http://localhost/dynamic365Build/en/dynamic/"
# baseURL = "https://amptest.ameio.in/"
languageCode = "en-us"
title = "My New Hugo Site"

[Languages]
############ 1 - Site en Japanese
[Languages.jp]
languageName = "JP"
weight = 1
languageCode = "jp-jp"

############ 1 - Site en Japanese
[Languages.en]
languageName = "EN"
weight = 2
languageCode = "en-en"


[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2